### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by bandit-masked** [anticitizn/mqtt-client#1]
Just wanted to say thanks for creating the MQTT Chat app with Dear PyGui. Not sure if you are active on the Discord server, so I thought this would be the easiest way to reach out.

Your app is now featured on the *Tools and Widgets* page.
https://github.com/hoffstadt/DearPyGui/wiki/Tools-and-Widgets#mqtt-chat

**Comment by anticitizn** [comment]
Thank you! That's awesome
